version: '3.8'

services:
  grimorio-app:
    build: .
    container_name: grimorio_webapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=192.168.0.153
      - DB_PORT=6532
      - DB_USER=leo
      - DB_PASSWORD=sua_senha_aqui
      - DB_NAME=postgres
      - SECURITY_PIN=1998
    # Se o PostgreSQL estiver no host ou na mesma rede local
    extra_hosts:
      - "host.docker.internal:host-gateway"
